### ISSUE TITLE
Externalize business logic from KeywordsController

### ISSUE THREAD

**Issue by olivierobert** [Tolsee/google-scrape-api#13]
`KeywordsController` does too much:
- Parsing CSV file
- Creating keywords in the database
- Scheduling background jobs

In brief, it's a fat controller which needs to be put on a diet to respect the single responsibility principles and to make it easy to test.

So prefer to externalize this logic to standalone Plain Old Ruby Objects (classes or modules). There are different patterns you could follow: service classes, form objects, non-ActiveRecord models or lib classes. For instance:

- app/services/parse_csv_service.rb: to parse CSV file
- app/forms/csv_upload_form.rb: validate the user input and create keywords. And maybe schedule a background job on success while this could be defined on an `after_commit` on the keyword model itself.

**Comment by Tolsee** [comment]
I totally agree on externalizing business logic from the controller. It makes testing easier as well as makes code more readable and maintainable as we grow. 

While I agree with that, I want to add:

- Actually CSV is parsed in the frontend and sent as an array on the backend.
- And, I am performing a batch worker rather than callbacks because I want to limit the requests to Google by put delays in between (though it's simple for now). If you see `GoogleScrapeBatchWorker` actually do that i.e. it will schedule `GoogleScrape` worker every other second. (Sidekiq actually does not provide Rate Limiting feature on the free version so I am trying to mimic that)

**Comment by Tolsee** [comment]
I hope the PR solves the issue.

**Comment by olivierobert** [comment]
> Actually CSV is parsed in the frontend and sent as an array on the backend.

Yes, you are right

> I am performing a batch worker rather than callbacks because I want to limit the requests

Makes sense

> Sidekiq actually does not provide Rate Limiting feature on the free version so I am trying to mimic that

Good point 😀

The only lacking part of the PR is testing for `ImportKeyword`.

Eventually, I would recommend you to look into [Form objects](https://medium.com/nimble/lets-play-design-patterns-form-objects-e06fe203f443) to externalize data validation and creation in controllers. It would allow to group:

- Validation: `validate_batch_params` now in the controller
- Creation: `import` now in `ImportKeyword`

**Comment by Tolsee** [comment]
First of all, sorry, I missed your comment. 

> Eventually, I would recommend you to look into Form objects to externalize data validation and creation in controllers. It would allow to group:

It looks exciting, I will surely give this pattern a try.

> The only lacking part of the PR is testing for ImportKeyword.

Yes, Sorry about that. Just got little busier. I will do it when I get time. Thanks for pointing out.
